---
abstract: 'A base class to make your very own Telegram bot'
author:
  - 'Justin Hawkins <justin@eatmorecode.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'manual'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Telegram-Bot
requires:
  IO::Socket::SSL: '2.037'
  Log::Any: '1.032'
  Mojolicious: '8.00'
  Test::Exception: '0.43'
resources:
  bugtracker: https://github.com/kk12l/Telegram-Bot/issues
  homepage: https://github.com/kk12l/Telegram-Bot
  repository: https://github.com/kk12l/Telegram-Bot.git
version: '0.022'
x_generated_by_perl: v5.26.1
x_serialization_backend: 'YAML::Tiny version 1.70'
